### ISSUE TITLE
'TrainingLog' object has no attribute '_implements_train_batch_hooks'

### ISSUE THREAD

**Issue by ghost** [autonomio/talos#498] opened 2020-07-22 15:15 UTC
#66 ## 1) Confirm the below

- Python version - 3.6.9

- Tensorflow version - 2.2.0

- I've tested my Keras model and it works as a stand-alone

#### 2) Include the output of:

`talos.__version__`  - 1.0.0

#### 3) Explain what actually happened

I am trying to perform hyperparameter tuning using the  TextCNN model and the IMDB Dataset on Colab. I followed the steps mentioned in one of the example notebooks on how to set up the required parameter space and run talos using the Scan() function.

The problem is when I try to execute the following statement:

`t = talos.Scan(x=X_train,
               y=y_train,
               model=build_model,
               params=p,
               experiment_name='sentiment_analysis',
               fraction_limit = 0.1)`

I am getting the following error message:

`AttributeError: 'TrainingLog' object has no attribute '_implements_train_batch_hooks'`

#### 5) Provide a code-complete reference

Input model:

![image](https://user-images.githubusercontent.com/68135192/88194137-16374580-cc5c-11ea-9ff8-6ba3efa23824.png)

Parameter dictionary:

`# then we can go ahead and set the parameter space
p = {'batch_size': [32, 64],
     'epochs': [50, 100],
     'kernel_initializer': ['uniform', 'normal', 'glorot_uniform', 'he_normal'],
     'optimizer': ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam'],
     'activation':['relu', 'elu'],
     }`

Please help me out with this. Am I doing something wrong? Also, how can I make use of the GPU/TPU facility provided in Colab. When I try to run the code using talos, it is using CPU and not GPU.

**Comment by fabero** [comment] 2020-08-04 14:28
Hi @shaksham-4176, I ran into this issue as well. 

As with many strange Tensorflow errors, this was caused by mixing `tensorflow.keras` with `keras`.

It appears that talos is using `keras`, so replacing all occurences of  `from tensorflow.keras import ...` with `from keras import ...` in your code will probably fix your issue (assuming you have standalone Keras installed).

**Comment by rsouza** [comment] 2020-10-21 11:50
> 
> 
> In Talos 1.0 onwards all imports should be already handled through tf.

Is it already working like this? I am still having the same problem (Talos 1.0, TensorFlow 2.3.1, no standalone Keras)
Thanks for the attention.

**Comment by mikkokotila** [comment] 2020-11-15 11:29
This is a known issue in an underlying package [Astetik](https://github.com/autonomio/astetik).

Will have to fix it there.

**Comment by mikkokotila** [comment] 2022-04-16 13:17
This has now been fixed in the underlying dependency. Closing here.

**Closed by mikkokotila** 2022-04-16 13:17 UTC
Labels: priority: HIGH, topic: upstream: astetik
