### ISSUE TITLE
Modification to run with multi-output models

### ISSUE THREAD

**Issue by JoshuaMitton** [autonomio/talos#154] opened 2018-12-14 12:33 UTC
It would be great if possible to allow the option of using multi-output Keras models. 

It is currently stated in Scan.py that y should have shape (m, c) where c is the number of classes. This restricts to one output parameter and inputting a multi-output model yields the following error:
~/.local/lib/python3.6/site-packages/talos/scan/scan_prepare.py in scan_prepare(self)
     57 
     58     # create the data asset
---> 59     self.y_max = self.y.max()
     60     self = validation_split(self)
     61     self.shape = classify(self.y)

AttributeError: 'list' object has no attribute 'max'

For example the model I am currently working with outputs Age, Species, and Status where each has a different value of c in the shape (m, c).

**Comment by JoshuaMitton** [comment] 2018-12-17 15:34
I have updated to the latest development version of Talos and this issue still persists. 

The output to my model is as follows:
`    xAge     = Dense(name = 'age', units = 17, 
                     activation = 'softmax', 
                     kernel_regularizer = l2(params['regage']), 
                     kernel_initializer = 'he_normal')(xd)
    xSpecies = Dense(name ='species', units = 3, 
                     activation = 'softmax', 
                     kernel_regularizer = l2(params['regspecies']), 
                     kernel_initializer = 'he_normal')(xd)
    xStatus  = Dense(name='status', units = 3, 
                     activation = 'softmax', 
                     kernel_regularizer = l2(params['regstatus']), 
                     kernel_initializer = 'he_normal')(xd)

    outputs = []
    for i in ['xAge', 'xSpecies', 'xStatus']:
        outputs.append(locals()[i])
    model = Model(inputs = input_vec, outputs = outputs)`

From the error message is appears that Talos looks for a max value of the y data. Given that this is a list of 3 numpy arrays it doesn't have a max and errors.

Can Talos be updated to handle multi-input / multi-output models?  Or is my understanding oh how to set this up incorrect?

I am calling Talos like this (also my model runs fine when not using Talos):
`h = ta.Scan(x=X_train, y=y_train, params=params,
            model = CNN_model,
            x_val=X_val, y_val=y_val,
            dataset_name='mosquito_CNN',
            experiment_no=str(fold),
            grid_downsample=0.01)`

**Comment by mikkokotila** [comment] 2018-12-19 10:57
can you share the CNN_model you are using as input for Scan()

**Comment by mikkokotila** [comment] 2019-01-18 16:34
I think this needs to be handled together with #145 and #155.

**Comment by rarazac** [comment] 2019-07-23 12:59
Any news on the support of multiple outputs?

**Comment by mikkokotila** [comment] 2019-07-23 14:25
To add small background, in my own research as well as that of our wider research group, implementing ethnical considerations is a key interest, and multi output models seem to be a good place to start.

**Comment by rarazac** [comment] 2019-07-23 16:02
@mikkokotila Thank you very much for your response! 

If the multiple output model uses the same labels, the following minimal example seems to work...

``` python

import talos as tl
import tensorflow as tf

def getModelForSweep(x_train, y_train, x_val, y_val, params):

    input_shape = (28, 28) # 28x28 pixels
    inp = tf.keras.layers.Input(shape=input_shape, name="main_input")

    # shared network
    shared_net = tf.keras.layers.Dense(params['shared_fc'], activation="relu")(inp)
    shared_network_out = tf.keras.layers.Flatten(name="shared_out")(shared_net)

    # out_1
    out_1 = tf.keras.layers.Dense(params['fc'])(shared_network_out)
    out_1 = tf.keras.layers.Dense(10, activation="softmax", name="out_1")(out_1)

    # out_2
    out_2 = tf.keras.layers.Dense(params['fc'])(shared_network_out)
    out_2 = tf.keras.layers.Dense(10, activation="softmax", name="out_2")(out_2)
    
    # build compile and train the model
    model = tf.keras.models.Model(inputs=inp, outputs=[out_1, out_2])
    model.compile(optimizer=params['optimizer'], 
                             metrics=['accuracy'],
                             loss={'out_1': tf.keras.losses.categorical_crossentropy,
                                   'out_2':tf.keras.losses.categorical_crossentropy})
    out = model.fit(x_train, [y_train, y_train], validation_split=0.1)

    return out, model

# parameters for sweep
p = {
    'lr': [0.01, 0.001, 0.0001],
    'shared_fc': [32, 64],
    'fc': [64, 128],
    'optimizer': ['Adam', 'sgd'],
}

# load data
(mnist_train, train_labels), (mnist_test, test_labels) = tf.keras.datasets.mnist.load_data()
train_labels_hot = tf.keras.utils.to_categorical(train_labels, num_classes=10)

# sweep
tl.Scan(x=mnist_train, y=train_labels_hot,
        params=p,
        model=getModelForSweep,
        grid_downsample=0.1, 
        experiment_no='1', 
        dataset_name='mnist')

```

**Comment by mikkokotila** [comment] 2019-07-24 10:49
Thanks. Given that this runs ok, do I gather it right that the issue is simply down to being able to pass two separate `y` in to `talos.Scan()`?

**Comment by mikkokotila** [comment] 2019-07-24 11:20
This is now implemented in daily-dev: 

`pip install git+https://github.com/autonomio/talos@daily-dev`

Below is a working example for reference:

```
import talos as tl
import tensorflow as tf

def getModelForSweep(x_train, y_train, x_val, y_val, params):

    input_shape = (28, 28) # 28x28 pixels
    inp = tf.keras.layers.Input(shape=input_shape, name="main_input")

    # shared network
    shared_net = tf.keras.layers.Dense(params['shared_fc'], activation="relu")(inp)
    shared_network_out = tf.keras.layers.Flatten(name="shared_out")(shared_net)

    # out_1
    out_1 = tf.keras.layers.Dense(params['fc'])(shared_network_out)
    out_1 = tf.keras.layers.Dense(10, activation="softmax", name="out_1")(out_1)

    # out_2
    out_2 = tf.keras.layers.Dense(params['fc'])(shared_network_out)
    out_2 = tf.keras.layers.Dense(10, activation="softmax", name="out_2")(out_2)
    
    # build compile and train the model
    model = tf.keras.models.Model(inputs=inp, outputs=[out_1, out_2])
    model.compile(optimizer=params['optimizer'], 
                             metrics=['accuracy'],
                             loss={'out_1': tf.keras.losses.categorical_crossentropy,
                                   'out_2':tf.keras.losses.categorical_crossentropy})
    out = model.fit(x=x_train,
                    y=[y_train[0], y_train[1]],
                    validation_data=[x_val, [y_val[0], y_val[1]]])

    return out, model

# parameters for sweep
p = {
    'lr': [0.01, 0.001, 0.0001],
    'shared_fc': [32, 64],
    'fc': [64, 128],
    'optimizer': ['Adam', 'sgd'],
}

# load data
(mnist_train, train_labels), (mnist_test, test_labels) = tf.keras.datasets.mnist.load_data()
train_labels_hot = tf.keras.utils.to_categorical(train_labels, num_classes=10)

# sweep
tl.Scan(x=mnist_train, y=[train_labels_hot, train_labels_hot],
        x_val=mnist_train, y_val=[train_labels_hot, train_labels_hot],
        params=p,
        model=getModelForSweep,
        fraction_limit=0.1, 
        experiment_name='mnist', clear_session=False)
```
Thanks a lot for @rarazac for inputs and example model.

**Comment by mikkokotila** [comment] 2019-07-24 11:22
One important point to note here, you must explicitly pass validation data (as opposed to using the split argument). This is consistent with multi-input models, where also Talos expects passing validation data explicitly.

**Comment by sarmadm** [comment] 2019-07-24 11:43
IF I have a list as: 

X_train = [ f0_train_tw, f1_train_tw, f2_train_tw, f3_train_tw , f4_one_tr, f5_train_preds , f6_train]

Y_train = [Y_oh_tr, Ymrs_train, Y_oh_tr]

and test

X_test = [ f0_test_tw, f1_test_tw, f2_test_tw, f3_test_tw , f4_test_tr, f5_test_preds , f6_test]

Y_train = [Y_oh_tr, Ymrs_train, Y_oh_tr]

is below is correct way to model.fit ? 

out = model.fit( x= [X_train[0] ,X_train[1],X_train[2] ,X_train[3] ,X_train[4] ,X_train[5] ,X_train[6]]
                , y=Y_train,
                epochs=150,
                batch_size=params['batch_size'],
              
                validation_data = [[X_test[0] ,X_test[1] ,X_test[2] ,X_test[3] ,X_test[4] ,X_test[5] ,X_test[6]], Y_test],
                
                callbacks = [chkpt_r, chkpt_c, chkpt_r2c, reduceLR] , class_weight =class_weight)

**Comment by mikkokotila** [comment] 2019-07-24 13:47
@sarmadm No, the above is not correct. Please see the provided example carefully and make effort to follow it. Also you can just copy paste the example and run on your machine, and then work from there to implement your own data and configuration in it.

**Comment by sarmadm** [comment] 2019-07-24 13:55
I tried to run the example but should I change

` out = model.fit(x=x_train,
                    y=[y_train[0], y_train[1], y_train[3]],
                    validation_data=[x_val, [y_val[0], y_val[1],y_val[2]]])
`

is it correct to change Y to this or X_train and X_train as well ?

**Comment by mikkokotila** [comment] 2019-07-25 17:22
@sarmadm as I had said, what you have to do is run the example provided on your system, and then work from there. If you would like to have user support for specific case of yours, then you could try and open a new issue for that. 

Closing this here as the actual matter is resolved, and the feature implemented and tested.

**Closed by mikkokotila** 2019-07-25 17:22 UTC
Labels: data-related, fixed-daily-dev, must have
