### ISSUE TITLE
local variable 'acc_entropy' referenced before assignment

### ISSUE THREAD

**Issue by dambuck** [autonomio/talos#120] opened 2018-10-26 15:48 UTC
Hi,

I hope it is appropriate to ask this question here, since I am not able to track the source of the error in my own code. The error occurs after a first scan round.
It is a variational autoencoder.

ofc_binned is the data and is of the shape (84,100,73)
I implemented two outputs only to test the loss_weights argument, because I got a different behaviour than putting both lost functions into one function. Batch_size is left to Default.

I must be doing something wrong because of the two outputs two losses and the fact that predict returns a list of length 2 and not directly the prediction array.... It works fine with a single output.

No problem with the network outside of Talos.

Thank you

steps=np.linspace(0.99,0.9999,30)
loss= {'weights': steps}

_____________________________________________________________
    def test_weights(x_train,y_train,x_val,y_val, params):
        def sampling(args):
            z_mean, z_var = args
            batch_size = K.shape(z_mean)[0]
            epsilon = K.random_normal(shape=(batch_size, latent_rep_size),mean=0.,stddev=epsilon_std)
            return z_mean + K.exp(z_var / 2) * epsilon 

    def LFADS_reg(true,out):
        kl = - 0.5 * K.sum(1 + z_var - K.square(z_mean) - K.exp(z_var), axis=-1)
        return kl
    
    def LFADS_poisson(true, predicted):
        true=K.flatten(true)
        predicted=K.flatten(predicted)
        return 1.*objectives.poisson(true, predicted)
    
    inp = Input(shape=(time_steps, neuron))
    encode = Bidirectional(LSTM(neuron, return_sequences=True, dropout=0.0, name='lstm_1'), merge_mode='concat')(inp)
    encode = Bidirectional(LSTM(neuron,  return_sequences=False, dropout=0.0, name='lstm_2'), merge_mode='concat')(encode)
   

    z_mean = Dense(latent_rep_size, name='z_mean', activation='linear')(encode)
    z_var = Dense(latent_rep_size, name='z_var', activation='linear')(encode)

    
    #sampling and reshaping into sequences
    decode=Lambda(sampling, output_shape=(latent_rep_size,), name='lambda')([z_mean, z_var])
    repeated_context = RepeatVector(time_steps)(decode) #time_steps=number of bins

    #'generator'
    decode = LSTM(neuron, return_sequences=True,dropout=0.0, name='generator_gt', activation='sigmoid')(repeated_context) 

    #calculate factors
    decode=TimeDistributed(Dense(20, activation='linear'), name='get_factors')(decode)
     decode=TimeDistributed(Dense(neuron,activation='linear'), name= 'pre_rates')(decode)
    decode=TimeDistributed(Dense(neuron, activation= K.exp ),name= 'exp_layer')(decode)

 
    nan=TerminateOnNaN()
    callbacklist=[nan]

    adam = optimizers.adam(clipvalue=100)
    Vae=Model(inputs=inp, outputs=[decode,decode])
    Vae.compile(optimizer='adam',loss= [LFADS_poisson,LFADS_reg], loss_weights=[params['weights'],1-params['weights']])
    out=Vae.fit(x_train, [y_train,y_train],epochs=10, callbacks=callbacklist)
    

    return out, Vae
____________________________________________________________________

talos_test = ta.Scan(ofc_binned, ofc_binned, loss,test_weights,functional_model=True)

____________________________________________________________________
AttributeError                            Traceback (most recent call last)
<ipython-input-110-881a4039c46d> in <module>()
----> 1 talos_test = ta.Scan(ofc_binned, ofc_binned, loss,test_weights,functional_model=True)

~/.local/lib/python3.5/site-packages/talos/scan/Scan.py in __init__(self, x, y, params, model, dataset_name, experiment_no, x_val, y_val, val_split, shuffle, round_limit, grid_downsample, random_method, seed, search_method, reduction_method, reduction_interval, reduction_window, reduction_threshold, reduction_metric, reduce_loss, last_epoch_value, talos_log_name, clear_tf_session, functional_model, disable_progress_bar, print_params, debug)
    164         # input parameters section ends
    165 
--> 166         self._null = self.runtime()
    167 
    168     def runtime(self):

~/.local/lib/python3.5/site-packages/talos/scan/Scan.py in runtime(self)
    169 
    170         self = scan_prepare(self)
--> 171         self = scan_run(self)

~/.local/lib/python3.5/site-packages/talos/scan/scan_run.py in scan_run(self)
     19                      disable=self.disable_progress_bar)
     20     while len(self.param_log) != 0:
---> 21         self = scan_round(self)
     22         self.pbar.update(1)
     23     self.pbar.close()

~/.local/lib/python3.5/site-packages/talos/scan/scan_round.py in scan_round(self)
     45 
     46     _hr_out = run_round_results(self, _hr_out)
---> 47     self._val_score = get_score(self)
     48     write_log(self)
     49     self.result.append(_hr_out)

~/.local/lib/python3.5/site-packages/talos/metrics/score_model.py in get_score(self)
     33         # for functional model experimental support
     34         if self.functional_model:
---> 35             y_pred = _functional_predict(self.keras_model, self.x_val)
     36         # all other cases
     37         else:

~/.local/lib/python3.5/site-packages/talos/metrics/score_model.py in _functional_predict(model, x, batch_size, verbose)
     11                           verbose=verbose)
     12 
---> 13     if proba.shape[-1] > 1:
     14         return proba.argmax(axis=-1)
     15     else:

AttributeError: 'list' object has no attribute 'shape'

**Comment by mikkokotila** [comment] 2018-10-28 12:32
This is caused by the fact that you use custom loss and there is no accuracy metric. That said, this should have been fixed in the more recent versions (and if it's not, I will do it asap). Could you check your Talos version: 

`pip show talos | grep Version`

What do you get?

**Comment by dambuck** [comment] 2018-10-29 08:59
I get:
Metadata-Version: 2.1
Version: 0.4.3

I should install the latest dev version then?

**Comment by mikkokotila** [comment] 2018-10-29 09:13
@dambuck Thanks. Can you try 0.4.4 which would be then:

```
pip uninstall talos 
pip install git+https://github.com/autonomio/talos@dev
```
NOTE: you don't anymore need to declare `functional_model=True` in 0.4.4. Also for clarity's sake, I suggest using explicit arguments in Scan() e.g. ta.Scan(model='...') as the input order was slightly changed.

**Comment by dambuck** [comment] 2018-10-29 09:50
@mikkokotila Thank you very much! Its working now.

**Closed** 2018-10-29 09:50 UTC
