### ISSUE TITLE
result logging confusion

### ISSUE THREAD

**Issue by tik0** [autonomio/talos#273] opened 2019-03-13 12:24 UTC
- [x] I'm up-to-date with the latest release (i.e. v.0.4.9 and all upcoming possibly):
- [x] I've confirmed that my Keras model works outside of Talos.

-------------------------------------------------------------------------

I found a crucial issue in the result logging (**i.e. `results.py` for all current an upcoming versions**). All results, as well as the headers are stored in a single list, which is the member object `self.result`, or temporary variable `_rr_out` respectively. However, to store the values, the dictionary keys are traversed and concatenated into the list. **And here comes the issue**: Python does not guarantee the order of keys in a dictionary! Therefore, it is possible that values like `acc` may become `acc_val`, or the `loss` value becomes a parameter, and so on.

It might be the case that this issue hardly happens for only a few metrics and parameters. But it definitely happens in my exhaustive evaluations with dozens of metrics and parameters.

However, this issue can be very easily fixed by using a dictionary instead of a list for storing the results. I already implemented this feature in my fork: https://github.com/tik0/talos/commit/8db906f0ca8498de963b0e3c787e58a721e9e395
(Please notice that this commit is a forked branch, which comes with disabled stringification (#271), user defined history (#272) and fixed entropy (#268))

This is a major issue from my point of view and I will elaborate on a patch for a PR if desired.

**Comment by mikkokotila** [comment] 2019-03-13 12:29
Thanks, that's great. This is related with #267. 

Do I understand correct, if we are using an ordered dictionary, and we take the keys from there once and then always refer to that wherever it might be required, the issue is resolved?

**Comment by tik0** [comment] 2019-03-13 12:35
This could be the case for your parameters which needs to be cast if a user hasn't defined it as an ordered dict. But you also have to cast the keras history object as well. I think this isn't a very elegant solution just for making your list approach work. As you can see in my commit, I just replaced the `self.result` list with the dictionary and just match the keys during the result update which is definitely the intended python way for what you want to do.

**Comment by tik0** [comment] 2019-03-13 12:37
> Thanks, that's great. This is related with #267.
> 
> Do I understand correct, if we are using an ordered dictionary, and we take the keys from there once and then always refer to that wherever it might be required, the issue is resolved?

Yes, my approach is a direct solution to issue #267. I haven't found it earlier, sorry.

**Comment by mikkokotila** [comment] 2019-03-13 12:41
Can you make a PR (to daily-dev) with just this the issue in #267 fixed. The stringification takes us to deeper topics, where it might be more meaningful to address the underlying problem all together. I could start working on a rebuild of logging as soon as we establish a clear picture of what would be the important criteria there. More on that in #271.

**Comment by tik0** [comment] 2019-03-13 13:35
I proposed a PR: #274. However, it comes naturally with disabled stringification, since there is really no need to stringify all objects inside a dictionary. As of version v.0.5.0, this might be a logical step.

**Comment by mikkokotila** [comment] 2019-06-14 05:33
Thanks. This part is handled now in a much improved matter as part of the move to the next LTS version which starts from v.0.6. You can start using it with: 

`pip install git+https://github.com/autonomio/talos`

Closing here.

**Closed by mikkokotila** 2019-06-14 05:33 UTC
Labels: logging-related, moderate priority fix

**Comment by tik0** [comment] 2019-06-17 07:50
> Thanks. This part is handled now in a much improved matter as part of the move to the next LTS version which starts from v.0.6. You can start using it with:
> 
> `pip install git+https://github.com/autonomio/talos`
> 
> Closing here.

Could you briefly describe how and where you have fixed the issue wrt. stringification and confusion of dictionaries?

**Comment by mikepm35** [comment] 2019-06-19 13:46
I was also encountering this issue, including with a daily-dev branch that included this fix.  If I look at that commit, the results are still stored in an unordered dictionary...
```
def _round_parameters_todict(self, values):

    round_parameters = {}

    for i, key in enumerate(self.param_keys):
        round_parameters[key] = values[i]

    return round_parameters
```

...that is then traversed to add a row
```
def run_round_results(self, out):
    ...
    # record the last epoch result
    for key in out.history.keys():
        _round_result_out.append(out.history[key][-1])

    # record the round hyper-parameters
    for key in self.round_params.keys():
        _round_result_out.append(self.round_params[key])
```

I went a different route in my own branch and put protections into place to ensure the right order and also catch any dropped keys: https://github.com/mikepm35/talos/commit/46e4787790882e93a247e1fcc0b323a69a73c068
