### ISSUE TITLE
Error: Classification metrics can't handle a mix of binary and continuous targets

### ISSUE THREAD

**Issue by egorrevkov** [autonomio/talos#169] opened 2019-01-15 10:36 UTC
Hi, I am having troubles optimizing a CNN model for a regression problem in Talos, and can't really figure out what exactly I'm doing wrong. I was following [this instruction](https://nbviewer.jupyter.org/github/autonomio/talos/blob/master/examples/Hyperparameter%20Optimization%20with%20Keras%20for%20the%20Iris%20Prediction.ipynb) to set it up.

My training and validation data (floats, 50/50 split of the original dataset) look like 
```
> x_train.shape
(3145, 250, 1)
> y_train.shape
(3145,)
> x_val.shape
(3146, 250, 1)
> y_val.shape
(3146,)
```

And my Keras model (which is working outside of Talos) is:
```python
def cnn_model(x_train, y_train, x_val, y_val, params):

    model = Sequential()

    model.add(
        Conv1D(
            filters=params['filters'],
            kernel_size=params['kernel_size'],
            activation=params['activation_first'],
            input_shape=(250, 1)))

    model.add(MaxPooling1D(pool_size=params['pool_size']))

    model.add(Dropout(rate=params['dropout_rate']))

    model.add(Flatten())

    model.add(
        Dense(units=params['units'], activation=params['activation_last']))

    model.compile(
        loss='mse',
        optimizer=params['optimizer'](
            lr=lr_normalizer(params['lr'], params['optimizer'])),
        metrics=['mse'])

    out = model.fit(
        gexpr_train_cnn,
        pur_train,
        epochs=20,
        batch_size=300,
        validation_data=[x_val, y_val],
        verbose=0)

    return out, model
```

Then, I define a space of hyperparameters (a simple grid, just to test how Talos works):
```python
p = {'lr': [0.1, 0.2],
    'filters': [64, 128],
    'activation_first': ['relu', 'softmax'],
    'activation_last': ['relu', 'softmax'],
    'kernel_size': [9],
    'dropout_rate': [0.1],
    'units': [1],
    'pool_size': [1],
    'optimizer': [Adam]}
```

I scan the grid with
```python
h = ta.Scan(x_train, y_train, params=p, model=cnn_model)
```
which completes the scan, and
```python
h.data.head()
```
returns
```
	round_epochs	val_loss	val_mean_squared_error	loss	mean_squared_error	lr	filters	activation_first	activation_last	kernel_size	dropout_rate	units	pool_size	optimizer
1	20	0.24956866435832897	0.24956866435832897	0.24007551897180382	0.24007551897180382	0.1	128	softmax	softmax	9	0.1	1	1	<class 'keras.optimizers.Adam'>
2	20	0.005563215427574212	0.005563215427574212	0.006587651558442448	0.006587651558442448	0.2	128	relu	relu	9	0.1	1	1	<class 'keras.optimizers.Adam'>
3	20	0.24956866435832897	0.24956866435832897	0.24007552033614477	0.24007552033614477	0.1	64	relu	softmax	9	0.1	1	1	<class 'keras.optimizers.Adam'>
4	20	0.006304671476847666	0.006304671476847666	0.007712373126948383	0.007712373126948383	0.1	128	relu	relu	9	0.1	1	1	<class 'keras.optimizers.Adam'>
5	20	0.017181661118106064	0.017181661118106064	0.018292305889793904	0.018292305889793904	0.2	64	softmax	relu	9	0.1	1	1	<class 'keras.optimizers.Adam'>
```
So I'm guessing that everything went well in the steps before.

But when I try to find the best model with
```python
e = ta.Evaluate(h)
e.evaluate(
    x_val, y_val, folds=10, average=None, metric='mean_squared_error')
```
I get an error:
```python
--------
ValueError                                Traceback (most recent call last)
<ipython-input-114-72dfe096093c> in <module>
      1 e = ta.Evaluate(h)
      2 e.evaluate(
----> 3     x_val, y_val, folds=10, average=None, metric='mean_squared_error')

/usr/local/lib/python3.6/dist-packages/talos/commands/evaluate.py in evaluate(self, x, y, model_id, folds, shuffle, average, metric, asc)
     38 
     39         for i in range(folds):
---> 40             y_pred = model.predict(kx[i]) >= 0.5
     41             scores = f1_score(y_pred, ky[i], average=average)
     42             out.append(scores * 100)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py in f1_score(y_true, y_pred, labels, pos_label, average, sample_weight)
    718     return fbeta_score(y_true, y_pred, 1, labels=labels,
    719                        pos_label=pos_label, average=average,
--> 720                        sample_weight=sample_weight)
    721 
    722 

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py in fbeta_score(y_true, y_pred, beta, labels, pos_label, average, sample_weight)
    832                                                  average=average,
    833                                                  warn_for=('f-score',),
--> 834                                                  sample_weight=sample_weight)
    835     return f
    836 

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py in precision_recall_fscore_support(y_true, y_pred, beta, labels, pos_label, average, warn_for, sample_weight)
   1029         raise ValueError("beta should be >0 in the F-beta score")
   1030 
-> 1031     y_type, y_true, y_pred = _check_targets(y_true, y_pred)
   1032     check_consistent_length(y_true, y_pred, sample_weight)
   1033     present_labels = unique_labels(y_true, y_pred)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py in _check_targets(y_true, y_pred)
     79     if len(y_type) > 1:
     80         raise ValueError("Classification metrics can't handle a mix of {0} "
---> 81                          "and {1} targets".format(type_true, type_pred))
     82 
     83     # We can't have more than one value on y_type => The set is no more needed

ValueError: Classification metrics can't handle a mix of binary and continuous targets
```
Just in case, I have tried playing around with different values for **average** and **asc** parameters of **evaluate**, didn't help. 

From what I can see, Talos is trying to use f_1 score from sklearn, but this is a classification metric, so it makes sense that it does not work for my data. Is there any way to make it use a regression metric (e.g. mse)? 

Overall, could you please help me to resolve this?

Many thanks,
Egor

**Comment by mikkokotila** [comment] 2019-01-15 16:38
Thanks for reporting this. It will be done most likely within the next 24 hour window.

**Comment by mikkokotila** [comment] 2019-01-16 14:37
Small update on this. 

I've explored the various ways in which we can support: 

- binary 
- multi_label
- multi_class
- regression

And additionally: 

- all sklearn metrics
- any custom metric

Turns out it's a little bit tricky to do this well without any magics (which I believe is important to avoid as much as possible) but I should have an update today or tomorrow.

**Comment by mikkokotila** [comment] 2019-01-16 18:49
I've implemented the support. It's using mae as a metric for regression. Also multi_label and multi_class is supported. Check the Evaluate.evaluate() docstring for full info. You can try it with 

`pip install git+https://github.com/autonomio/talos@daily-dev`

Bare in mind that this is still experimental in the sense that it has not been robustly tested with many datasets. That would have to happen before it moves to dev and eventually master/production.

**Comment by egorrevkov** [comment] 2019-01-17 07:55
Thanks for looking in into it and fixing!

The Evaluate.evaluate() method is working now. However, I have a couple of questions, would be really helpful if you could anwser them.

1.
 ```python
e = ta.Evaluate(h)
e.evaluate(
    x_val,
    y_val,
    folds=10,
    metric='mean_squared_error',
    mode='regression',
    print_out=True)
```
returns
```python
mean : 0.46 
 std : 0.01
[0.4518117945302803,
 0.4725303323616019,
 0.4496370901497834,
 0.4615459235263695,
 0.4770823200189714,
 0.4690325974030223,
 0.4575328185155446,
 0.4670078357595127,
 0.46224965342613067,
 0.4520023687112262]
```
What does the output mean exactly? I guess these may be results of the 10-fold cross-validation on my **x_val** and **y_val** data, but which of the models is being tested, the best one?

Also, the docstring seems to be slightly wrong: it mentions **sort_metric : string** parameter, but the function expects **metric : string** instead.

2. My initial goal is to find the best hyperparameters, so I tried doing it using **Reporting** class:
```python
r = ta.Reporting(h)
r.best_params(metric='mean_squared_error', n=1, ascending=True)
```
returns
```python
array([['1', '0.2', '9', '128', 'relu', '1', '0.1',
        "<class 'keras.optimizers.Adam'>", 'relu', 0]], dtype=object)
``` 
So it seems to be working! 
I still have a couple of questions, though:

   1) **best_params** docstring says that it "Adds an index as the last column". What index should it be? Right now it seems as it's just an index of order in which the method prints the results. I guess it could be useful if it indicated the index of the best model...

   2) Also, is there a way to understand which values refer to which hyperparameters in the array that **best_params** outputs? If I have several hyperparameters with the same possible values, it might be difficult to decipher where they belong without the keys.

Overall, I might be going in the wrong direction, so again: I would like to find the hyperparameters of the best model. Could you please advise the right approach to get them for sure, with little confusion?

Many thanks for your help,
Egor

**Comment by mikkokotila** [comment] 2019-01-17 08:22
Great that you can now use Evaluate.evaluate(). 

Regarding your questions, there is the issue #149 which will resolve this. I'm moving my reply there so it stays in one place. Closing here as this is resolved.

**Closed** 2019-01-18 15:56 UTC
Labels: high priority fix

**Comment by egorrevkov** [comment] 2019-02-08 02:54
Reopening the issue since I've stubled onto something that I think is related to your fix:

Basically, my analysis is the same before, although I split my data into  training and validation sets manually for this step.

I want to perform cross-evaluation for my regression models.
When I run
```python
h.evaluate_models(x_val, y_val, metric='val_mean_squared_error', folds=10, asc=True)
```
I get the following error:
```python
TypeError                                 Traceback (most recent call last)
<ipython-input-38-c2de9189d576> in <module>
----> 1 h.evaluate_models(x_val, y_val, metric='val_mean_squared_error', folds=10, asc=True)

/usr/local/lib/python3.6/dist-packages/talos/scan/scan_addon.py in func_evaluate(scan_object, x_val, y_val, n, metric, folds, shuffle, average, asc)
     61                                              shuffle=shuffle,
     62                                              average=average,
---> 63                                              asc=asc)
     64             out.append([mean(temp), std(temp)])
     65             pbar.update(1)

TypeError: evaluate() got an unexpected keyword argument 'average'
```

I guess it could be related to the fix to the _evaluate()_ method you'd pushed above (since before that _average_ really was its argument)?

**Comment by WilfriedOdi** [comment] 2020-04-23 21:57
ValueError: Classification metrics can't handle a mix of unknown and binary targets

**Comment by linehammer** [comment] 2021-07-26 06:43
accuracy_score is a classification metric, you cannot use it for a regression problem.  You get the error because these [regression model](http://net-informations.com/ds/mla/default.htm) do not produce binary outcomes, but continuous (float) numbers (as all regression model do); so, when scikit-learn attempts to calculate the accuracy by comparing a binary number (true label) with a float (predicted value), it not unexpectedly gives an error. And this cause is clearly hinted at the error message itself:

The sklearn.metrics.accuracy_score(y_true, y_pred) method defines y_pred as:

y_pred : 1d array-like, or label indicator array / sparse matrix. Predicted labels, as returned by a classifier.

Which means y_pred has to be an array of 1's or 0's (predicated labels). They should not be probabilities.
