### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Kinzerfest** [autonomio/talos#119] opened 2018-10-26 00:34 UTC
Thanks so much for coming here to raise an issue. Please take a moment to 'check' the below boxes:

- [yes] I'm up-to-date with the latest release:
    
      pip install -U talos

- [yes] I've confirmed that my Keras model works outside of Talos.

If you still have an error, please submit **complete trace** and a code with: 

- output of shape for x and y e.g. (212,12)
- Talos params dictionary
- The Keras model wired for Talos
- Description of extra variables in the model

You can provide the code in pastebin / gist or any other format you like. 

-------------------------------------------------------------------------

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-42-957bd11ed7b1> in <module>()
     94 
     95 h = ta.Scan(X, Y, params=p,
---> 96             model=gen_model_param)
     97 
     98 

/usr/local/lib/python3.6/dist-packages/talos/scan/Scan.py in __init__(self, x, y, params, model, dataset_name, experiment_no, x_val, y_val, val_split, shuffle, round_limit, grid_downsample, random_method, seed, search_method, reduction_method, reduction_interval, reduction_window, reduction_threshold, reduction_metric, reduce_loss, last_epoch_value, talos_log_name, clear_tf_session, functional_model, disable_progress_bar, print_params, debug)
    164         # input parameters section ends
    165 
--> 166         self._null = self.runtime()
    167 
    168     def runtime(self):

/usr/local/lib/python3.6/dist-packages/talos/scan/Scan.py in runtime(self)
    168     def runtime(self):
    169 
--> 170         self = scan_prepare(self)
    171         self = scan_run(self)

/usr/local/lib/python3.6/dist-packages/talos/scan/scan_prepare.py in scan_prepare(self)
     41 
     42     # create the paramater object and move to self
---> 43     self.paramgrid_object = ParamGrid(self)
     44     self.param_log = self.paramgrid_object.param_log
     45     self.param_grid = self.paramgrid_object.param_grid

/usr/local/lib/python3.6/dist-packages/talos/parameters/ParamGrid.py in __init__(self, main_self)
     23 
     24         # build the parameter permutation grid
---> 25         self.param_grid = self._param_grid()
     26 
     27         # reduce according to downsample

/usr/local/lib/python3.6/dist-packages/talos/parameters/ParamGrid.py in _param_grid(self)
     44         '''
     45 
---> 46         ls = [list(self._p[key]) for key in self._p.keys()]
     47         _param_grid_out = array(list(product(*ls)))
     48 

/usr/local/lib/python3.6/dist-packages/talos/parameters/ParamGrid.py in <listcomp>(.0)
     44         '''
     45 
---> 46         ls = [list(self._p[key]) for key in self._p.keys()]
     47         _param_grid_out = array(list(product(*ls)))
     48 

TypeError: 'NoneType' object is not iterable
```

```
p = {'lr': (None),
     'first_neuron': [4, 8, 16, 32, 64, 128],
     'hidden_neurons': [4, 8, 16, 32, 64, 128],
     'hidden_layers': [2, 3, 4, 5, 6],
     'batch_size': [2, 3, 4],
     'epochs': [300],
     'dropout': (None),
     'weight_regulizer': [None],
     'emb_output_dims': [None],
     'optimizer': ['adam', 'nadam'],
     'losses': ['binary_crossentropy'],
     'activation': ['relu'],
     'last_activation': ['softmax']}
```

```
def gen_model_param(x_train, y_train, x_val, y_val, params):
  model = Sequential()
  model.add(Dense(params['first_neuron'], input_dim=x_train.shape[1], activation=params['activation']))
  for _ in range(params['hidden_layers']):
    model.add(Dense(params['hidden_neurons'], activation=params['activation']))
  model.add(Dense(1, activation=params['last_activation']))
  model.compile(loss = "binary_crossentropy", optimizer=params['optimizer'], metrics=['accuracy'])
  out = model.fit(x_train, y_train, validation_data=[x_val, y_val], epochs=params['epochs'], batch_size=params['batch_size'], verbose=0, callbacks=early_stopper(params['epochs'], mode='strict'))
  return out,model
```

**Comment by Kinzerfest** [comment] 2018-10-26 00:37
```
h = ta.Scan(X, Y, params=p,
            model=gen_model_param,
            grid_downsample=.01)
```
Sorry here is the way to run it execution.

Also, is this the correct way to implement variable number of hidden layers? I don't think I find it in the documentation

**Comment by mikkokotila** [comment] 2018-10-28 12:29
I think the error is caused by the tuple with value None in your params dictionary (for dropout). Try replacing that with [None] or removing the line all together. 

For hidden layers, see [in the corresponding section](https://autonomio.github.io/docs_talos/#hidden-layers) in the user guide. We have a helper function to handle hidden layers. But I think that the way you are doing it as well, might work.

**Comment by mikkokotila** [comment] 2018-11-09 13:45
Closing here.

**Closed by mikkokotila** 2018-11-09 13:45 UTC
