### ISSUE TITLE
Cant plot r.plot_kde('val_loss') AttributeError: Unknown property cbar

### ISSUE THREAD

**Issue by hadaev8** [autonomio/talos#254] opened 2019-03-03 10:42 UTC
Full code
https://colab.research.google.com/drive/1XBMF3tOQwRLuPrGJib-YkN20_9nmMVT4?authuser=3#scrollTo=Cgi6jl_6R6fj&line=17&uniqifier=1

**Comment by mikkokotila** [comment] 2019-03-03 10:43
I think you have to share the notebook with me, it says "401 credentials error".

**Comment by hadaev8** [comment] 2019-03-03 10:44
Fixed

**Comment by mikkokotila** [comment] 2019-03-03 10:59
still same

**Comment by hadaev8** [comment] 2019-03-03 11:07
Maybe need to create new link
https://colab.research.google.com/drive/1XBMF3tOQwRLuPrGJib-YkN20_9nmMVT4?authuser=3#scrollTo=Cgi6jl_6R6fj&line=17&uniqifier=1

**Comment by hadaev8** [comment] 2019-03-03 11:09
Okay, its still same link, its work on my other browser without login, but doesnt work on another device.

**Comment by mikkokotila** [comment] 2019-03-03 11:11
This link works: https://colab.research.google.com/drive/1XBMF3tOQwRLuPrGJib-YkN20_9nmMVT4

Your original link specifically mentions authorization.

**Comment by mikkokotila** [comment] 2019-03-03 11:15
What do you get with `matplotlib.__version__` in that notebook?

**Comment by hadaev8** [comment] 2019-03-03 11:17
'3.0.2'

**Comment by mikkokotila** [comment] 2019-03-03 11:17
Can you try installing something starting with 2 instead and see what happens.

**Comment by hadaev8** [comment] 2019-03-03 11:28
'xtick.labelbottom is not a valid rc parameter. See rcParams.keys() for a list of valid parameters.'
On 2.1.2
On 2.2.4 i get some graphs but still get error Unknown property cbar

**Comment by mikkokotila** [comment] 2019-03-03 11:45
How about `matplotlib==1.5.3`

**Comment by hadaev8** [comment] 2019-03-03 11:47
KeyError: 'axes.titlepad'

**Comment by mikkokotila** [comment] 2019-03-03 12:37
The issue is now fixed. If you start your notebook with: 

!pip install git+https://github.com/autonomio/talos@daily-dev
!pip install git+https://github.com/mikkokotila/astetik

But note that you must have astetik v.1.9.7 ... for some reason I was able to achieve this only with the above code on colab, even though that's the current pypi version. 

The issue was that Seaborn (which is underlying astetik which is the plot API for Talos) had moved colorbar related arguments from sns.kdeplot(). The v.1.9.7 version of astetik resolves that.

Closing here.

**Closed by mikkokotila** 2019-03-03 12:37 UTC
Labels: Reporting(), low priority fix

**Comment by hadaev8** [comment] 2019-03-06 10:10
I get now unhashable type: '_ColorPalette' with astetik

**Comment by mikkokotila** [comment] 2019-03-06 10:11
Can you share the whole trace?

**Comment by hadaev8** [comment] 2019-03-06 10:12
11 
     12 # heatmap correlation
---> 13 r.plot_corr()
     14 
     15 # a four dimensional bar grid

/usr/local/lib/python3.6/dist-packages/talos/commands/reporting.py in plot_corr(self, metric, color_grades)
     98         cols = self._cols(metric)
     99 
--> 100         return corr(self.data[cols], color_grades=color_grades)
    101 
    102     def plot_regs(self, x='val_acc', y='val_loss'):

/usr/local/lib/python3.6/dist-packages/astetik/plots/corr.py in corr(data, corr_method, annot, mask, line_width, line_color, color_grades, auto_sizing, palette, style, dpi, title, sub_title, x_label, y_label, legend, x_scale, y_scale, x_limit, y_limit, save)
    166                     linecolor=line_color,
    167                     cmap=palette,
--> 168                     annot=annot)
    169 
    170     # HEADER

/usr/local/lib/python3.6/dist-packages/seaborn/matrix.py in heatmap(data, vmin, vmax, cmap, center, robust, annot, fmt, annot_kws, linewidths, linecolor, cbar, cbar_kws, cbar_ax, square, ax, xticklabels, yticklabels, mask, **kwargs)
    494     if square:
    495         ax.set_aspect("equal")
--> 496     plotter.plot(ax, cbar_ax, kwargs)
    497     return ax
    498 

/usr/local/lib/python3.6/dist-packages/seaborn/matrix.py in plot(self, ax, cax, kws)
    258         # Draw the heatmap
    259         mesh = ax.pcolormesh(self.plot_data, vmin=self.vmin, vmax=self.vmax,
--> 260                              cmap=self.cmap, **kws)
    261 
    262         # Set the axis limits

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1808                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1809                         RuntimeWarning, stacklevel=2)
-> 1810             return func(ax, *args, **kwargs)
   1811 
   1812         inner.__doc__ = _add_data_doc(inner.__doc__,

/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_axes.py in pcolormesh(self, alpha, norm, cmap, vmin, vmax, shading, antialiased, *args, **kwargs)
   6000             raise ValueError(
   6001                 "'norm' must be an instance of 'mcolors.Normalize'")
-> 6002         collection.set_cmap(cmap)
   6003         collection.set_norm(norm)
   6004         collection.set_clim(vmin, vmax)

/usr/local/lib/python3.6/dist-packages/matplotlib/cm.py in set_cmap(self, cmap)
    340         cmap : colormap or registered colormap name
    341         """
--> 342         cmap = get_cmap(cmap)
    343         self.cmap = cmap
    344         self.changed()

/usr/local/lib/python3.6/dist-packages/matplotlib/cm.py in get_cmap(name, lut)
    172         return name
    173 
--> 174     if name in cmap_d:
    175         if lut is None:
    176             return cmap_d[name]

TypeError: unhashable type: '_ColorPalette'

**Comment by mikkokotila** [comment] 2019-03-06 10:15
Can you report anything do with plotting to https://github.com/mikkokotila/astetik as its caused there. This is related with a [known bug in Seaborn](https://github.com/mwaskom/seaborn/issues/1546).

**Comment by hadaev8** [comment] 2019-03-06 11:32
So, you wanna me to post issues on astetik or wait until they will fix it in seaborn?

**Comment by mikkokotila** [comment] 2019-03-06 11:33
That's right, a temporary fix can be implemented on the Astetik level for the short-term.

**Comment by hadaev8** [comment] 2019-03-06 11:36
I'm still confused, do you mean I need post this issues on astectik or new time then I will have issues with plotting I need post in on astetik repo?
(just don't know how your work organized)

**Comment by mikkokotila** [comment] 2019-03-06 11:39
Can you post this to Astetik. If you find new issues, create a new issue in Talos.
